#include <cstdio>
#include "pico_ql_swill_access_func.h"

namespace picoQL {

const char error_page_bytes[] = {
"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01//EN\" \"http://www.w3.org/TR/html4/strict.dtd\">\n"
"<html><head>\n"
"<title>Result Codes</title>\n"
"<style type=\"text/css\">\n"
"body {\n"
"    margin: auto;\n"
"    font-family: Verdana, sans-serif;\n"
"    padding: 8px 1%;\n"
"}\n"
"\n"
"a { color: #044a64 }\n"
"a:visited { color: #734559 }\n"
"\n"
".logo { position:absolute; margin:3px; }\n"
".tagline {\n"
"  float:right;\n"
"  text-align:right;\n"
"  font-style:italic;\n"
"  width:300px;\n"
"  margin:12px;\n"
"  margin-top:58px;\n"
"}\n"
"\n"
".toolbar {\n"
"  text-align: center;\n"
"  line-height: 1.6em;\n"
"  margin: 0;\n"
"  padding: 0px 8px;\n"
"}\n"
".toolbar a { color: white; text-decoration: none; padding: 6px 12px; }\n"
".toolbar a:visited { color: white; }\n"
".toolbar a:hover { color: #044a64; background: white; }\n"
"\n"
".content    { margin: 5%; }\n"
".content dt { font-weight:bold; }\n"
".content dd { margin-bottom: 25px; margin-left:20%; }\n"
".content ul { padding:0px; padding-left: 15px; margin:0px; }\n"
"\n"
"/* rounded corners */\n"
".se  { background: url(../images/se.gif) 100% 100% no-repeat #044a64}\n"
".sw  { background: url(../images/sw.gif) 0% 100% no-repeat }\n"
".ne  { background: url(../images/ne.gif) 100% 0% no-repeat }\n"
".nw  { background: url(../images/nw.gif) 0% 0% no-repeat }\n"
"\n"
"/* Things for \"fancyformat\" documents start here. */\n"
".fancy img+p {font-style:italic}\n"
".fancy .codeblock i { color: darkblue; }\n"
".fancy h1,.fancy h2,.fancy h3,.fancy h4 {font-weight:normal;color:#044a64}\n"
".fancy h2 { margin-left: 10px }\n"
".fancy h3 { margin-left: 20px }\n"
".fancy h4 { margin-left: 30px }\n"
".fancy th {white-space:nowrap;text-align:left;border-bottom:solid 1px #444}\n"
".fancy th, .fancy td {padding: 0.2em 1ex; vertical-align:top}\n"
".fancy #toc a        { color: darkblue ; text-decoration: none }\n"
".fancy .todo         { color: #AA3333 ; font-style : italic }\n"
".fancy .todo:before  { content: 'TODO:' }\n"
".fancy p.todo        { border: solid #AA3333 1px; padding: 1ex }\n"
".fancy img { display:block; }\n"
".fancy :link:hover, .fancy :visited:hover { background: wheat }\n"
".fancy p,.fancy ul,.fancy ol { margin: 1em 5ex }\n"
".fancy li p { margin: 1em 0 }\n"
"/* End of \"fancyformat\" specific rules. */\n"
"\n"
"</style>\n"
"<meta http-equiv=\"content-type\" content=\"text/html; charset=UTF-8\">\n"
"  \n"
"</head>\n"
"<body>\n"
"<div><!-- container div to satisfy validator -->\n"
"  \n"
"<h2>Result Codes</h2><blockquote><pre>\n"
"#define SQLITE_OK           0   /* Successful result */\n"
"/* beginning-of-error-codes */\n"
"#define SQLITE_ERROR        1   /* SQL error or missing database */\n"
"#define SQLITE_INTERNAL     2   /* Internal logic error in SQLite */\n"
"#define SQLITE_PERM         3   /* Access permission denied */\n"
"#define SQLITE_ABORT        4   /* Callback routine requested an abort */\n"
"#define SQLITE_BUSY         5   /* The database file is locked */\n"
"#define SQLITE_LOCKED       6   /* A table in the database is locked */\n"
"#define SQLITE_NOMEM        7   /* A malloc() failed */\n"
"#define SQLITE_READONLY     8   /* Attempt to write a readonly database */\n"
"#define SQLITE_INTERRUPT    9   /* Operation terminated by sqlite3_interrupt()*/\n"
"#define SQLITE_IOERR       10   /* Some kind of disk I/O error occurred */\n"
"#define SQLITE_CORRUPT     11   /* The database disk image is malformed */\n"
"#define SQLITE_NOTFOUND    12   /* Unknown opcode in sqlite3_file_control() */\n"
"#define SQLITE_FULL        13   /* Insertion failed because database is full */\n"
"#define SQLITE_CANTOPEN    14   /* Unable to open the database file */\n"
"#define SQLITE_PROTOCOL    15   /* Database lock protocol error */\n"
"#define SQLITE_EMPTY       16   /* Database is empty */\n"
"#define SQLITE_SCHEMA      17   /* The database schema changed */\n"
"#define SQLITE_TOOBIG      18   /* String or BLOB exceeds size limit */\n"
"#define SQLITE_CONSTRAINT  19   /* Abort due to constraint violation */\n"
"#define SQLITE_MISMATCH    20   /* Data type mismatch */\n"
"#define SQLITE_MISUSE      21   /* Library used incorrectly */\n"
"#define SQLITE_NOLFS       22   /* Uses OS features not supported on host */\n"
"#define SQLITE_AUTH        23   /* Authorization denied */\n"
"#define SQLITE_FORMAT      24   /* Auxiliary database format error */\n"
"#define SQLITE_RANGE       25   /* 2nd parameter to sqlite3_bind out of range */\n"
"#define SQLITE_NOTADB      26   /* File opened that is not a database file */\n"
"#define SQLITE_ROW         100  /* sqlite3_step() has another row ready */\n"
"#define SQLITE_DONE        101  /* sqlite3_step() has finished executing */\n"
"/* end-of-error-codes */\n"
"</pre></blockquote><p>\n"
"Many SQLite functions return an integer result code from the set shown\n"
"here in order to indicates success or failure.</p>\n"
"\n"
"<p>New error codes may be added in future versions of SQLite.</p>\n"
};
int len = sizeof(error_page_bytes);

void error_page(FILE *fo) {
  fwrite(error_page_bytes, len, 1, fo);
}

}  // namespace picoQL
